import { Layout } from "@/components/layout/Layout"
import type { Metadata } from "next"
import { Outfit } from "next/font/google"
import "./globals.css"
import { MainProvider } from "@/providers/MainProvider"

const OutfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
  weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OutfitFont.variable} antialiased`}
      >
        <MainProvider>
          <Layout>
            {children}
          </Layout>
        </MainProvider>
      </body>
    </html>
  );
}
